#include "bsp_clock.h"

// SystemClock_Config (168 MHz) is generated by CubeMX in Core/Src/main.c.
// This module exists as a placeholder should we later need to expose
// clock-related helpers (e.g., runtime reconfiguration, DWT cycle-counter setup).

void bsp_clock_init_168mhz(void)
{
}
