#include "bsp_gpio.h"

// Pin configuration for TIM1 PWM outputs, ADC input, and EXTI button
// is owned by Core/Src/gpio.c (generated by CubeMX from the .ioc).
// LEDs are initialized in bsp_led.c to guarantee PD12-15 mapping regardless of .ioc state.

void bsp_gpio_init(void)
{
}
